// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv1efMkQaLg53xD4cIeJhjY-WCAhEL98E',
    appId: '1:461110225601:web:a60da9ea13978e40ca4240',
    messagingSenderId: '461110225601',
    projectId: 'anonim-chat-bee39',
    authDomain: 'anonim-chat-bee39.firebaseapp.com',
    storageBucket: 'anonim-chat-bee39.firebasestorage.app',
    measurementId: 'G-ENH19N203H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAET72pMyEgZbV1twEqQmrOfBJjauLSs8M',
    appId: '1:461110225601:android:c61c36ed4221336dca4240',
    messagingSenderId: '461110225601',
    projectId: 'anonim-chat-bee39',
    storageBucket: 'anonim-chat-bee39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa9Qz1OFZRh9Loh7jRnpnGwRgggwJBwks',
    appId: '1:461110225601:ios:2c3473b32d3a5393ca4240',
    messagingSenderId: '461110225601',
    projectId: 'anonim-chat-bee39',
    storageBucket: 'anonim-chat-bee39.firebasestorage.app',
    iosBundleId: 'com.example.anonimChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa9Qz1OFZRh9Loh7jRnpnGwRgggwJBwks',
    appId: '1:461110225601:ios:2c3473b32d3a5393ca4240',
    messagingSenderId: '461110225601',
    projectId: 'anonim-chat-bee39',
    storageBucket: 'anonim-chat-bee39.firebasestorage.app',
    iosBundleId: 'com.example.anonimChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv1efMkQaLg53xD4cIeJhjY-WCAhEL98E',
    appId: '1:461110225601:web:5d248d77acfc7404ca4240',
    messagingSenderId: '461110225601',
    projectId: 'anonim-chat-bee39',
    authDomain: 'anonim-chat-bee39.firebaseapp.com',
    storageBucket: 'anonim-chat-bee39.firebasestorage.app',
    measurementId: 'G-ZT1CQVNJSQ',
  );
}
